import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Google Photos Search Insights",
  description: "Ask questions about Google Photos search/retrieval problems, grounded in real evidence.",
};

// Same localStorage key as public/insights.html and public/what-people-say.html,
// so switching theme on any page keeps the others in sync when you navigate
// between them. This runs before paint (a plain inline script, not an
// effect) so there's no flash of the wrong theme on load.
//
// Also redirects a REFRESH (not a normal click-through, not back/forward)
// back to Insights -- Insights is meant to be the one entry point, so
// reloading mid-chat on /ask drops you back there instead of restarting
// the same empty chat in place. This layout only wraps the /ask page (the
// other two screens are served as standalone HTML and carry the same
// check themselves, generated by atlas/build_pages.py), so it's safe to
// run unconditionally here.
const THEME_INIT_SCRIPT = `
(function(){
  try {
    var saved = localStorage.getItem('retrieval-atlas-theme');
    if (saved === 'light' || saved === 'dark') {
      document.documentElement.setAttribute('data-theme', saved);
    }
  } catch (e) {}
  try {
    var entries = performance.getEntriesByType('navigation');
    var navType = entries.length ? entries[0].type : null;
    if (navType === 'reload' && location.pathname !== '/') {
      location.replace('/');
    }
  } catch (e) {}
})();
`;

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&family=Roboto+Mono:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
        <script dangerouslySetInnerHTML={{ __html: THEME_INIT_SCRIPT }} />
      </head>
      <body>{children}</body>
    </html>
  );
}
